### PR TITLE
Update docker build to use mongo-express repo

### PR DESCRIPTION
**Pull request by BlackthornYugen**
I don't have permission to push to fitzrev/fix-build so I created this for now for reference. See #107 

This change will build from the mongo-express repo instead of using the version deployed to NPM. It also fixes a bug in generate-stackbrew-library.sh

### CODE REVIEW

**Comment by rtritto** [comment]
I got:
```console
[FATAL tini (2)] exec /docker-entrypoint.sh failed: Permission denied
```
Fixed in _Dockerfile_ adding `RUN chmod +x /docker-entrypoint.sh` after `COPY docker-entrypoint.sh /`

---
Instead of copy all `/app` content, should we copy only these?
```
.yarn
lib
node_modules
public
.yarnrc.yml
app.js
build-assets.json
config.default.js
package.json
webpack.config.js
yarn.lock
```
In future we can consider to produce a _dist_ folder to use for copy (builds of Docker image and npm).

**Comment by BlackthornYugen** [comment]
I thought that I tested that it was working last night; but maybe I forgot to build the latest changes or something. Now I can see a message that looks mostly good (except it says version 1.0.0): 

```
2024-01-03 07:59:53 No custom config.js found, loading config.default.js
2024-01-03 07:59:53 Welcome to mongo-express 1.0.0
2024-01-03 07:59:53 ------------------------
2024-01-03 07:59:53 
2024-01-03 07:59:53 
2024-01-03 07:59:54 Mongo Express server listening at http://localhost:8081
2024-01-03 07:59:54 Wed, 03 Jan 2024 12:59:54 GMT express-session deprecated req.secret; provide secret option at file:/app/lib/router.js:84:17
2024-01-03 07:59:54 Basic authentication is disabled. It is recommended to set the useBasicAuth to true in the config.js.
```

But when I try to reach the server I get no response: 

```
curl localhost:8081 --verbose --ipv4
```

```
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081
> GET / HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/8.4.0
> Accept: */*
> 
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

**Comment by BlackthornYugen** [comment]
My current workflow:

1. Change something in the template
2. Apply the template with
```
bash -x ./update.sh 1.0
```
3. Build any of the dockerfiles tagged as mongo-express
```
docker build --tag mongo-express 1.0/20-alpine3.18
```
4. Update compose
```
docker-compose up -d
```
5. Test
```
curl localhost:8081 --verbose --ipv4
```

**Comment by BlackthornYugen** [comment]
@rtritto @shakaran can you double check that I haven't removed any files that shouldn't have been removed? 

I think `manifest.yml` was only for direct cloud foundry deployments, is it needed for the docker image? 

`cypress.config.mjs` is just for tests I think?

```
docker run -it --rm mongo-express sh -c 'tail -n30 *.log'
```

```
==> removed-dirs.log <==
The following folders were removed to save space:
./.github
./cypress
./.bluemix
./.nyc_output
./test
./.git

==> removed-files.log <==
The following files were removed to save space:
./.gitignore
./.eslintrc.yml
./HISTORY.md
./SECURITY.md
./.gitattributes
./.mocharc.yml
./README.md
./manifest.yml
./.eslintignore
./Dockerfile
./.npmignore
./.dockerignore
./.cfignore
./cypress.config.mjs
```

**Comment by rtritto** [comment]
Why `RUN npm version "$(git describe --tags --dirty)" --no-git-tag-version` is needed? _yarn_ is used as package manager.

---

> Removing the folders saves 1MB of space but the files don't really save much, just makes it cleaner. Maybe we should put off this optimization until a future release so there are not any unintended consequences. The difference is like... 281MB vs 282MB.

Yes, in this PR, we can choose to not ignore other files.

**Comment by BlackthornYugen** [comment]
> Why `RUN npm version "$(git describe --tags --dirty)" --no-git-tag-version` is needed? _yarn_ is used as package manager.

I'm just using NPM to change the version in package.json. The yarn version command doesn't seem to let me do this. with a full version, it wants to bump major/minor or patch. Do you know the syntax?

**Comment by BlackthornYugen** [comment]
> Why `RUN npm version "$(git describe --tags --dirty)" --no-git-tag-version` is needed? _yarn_ is used as package manager.

If we don't like using npm for this, we can use jq, but I can't figure out how to do it with yarn. Here's how it might be done with jq:

```
RUN jq '.version=$VERSION' package.json --arg VERSION "$(git describe --tags --dirty)" | sponge package.json
```

or without sponge

```
RUN jq '.version=$VERSION' package.json --arg VERSION "$(git describe --tags --dirty)" > package.json.new ; \
    mv package.json.new package.json
```

**Comment by rtritto** [comment]
Should be `RUN yarn version "$(git describe --tags --dirty)"`

**Comment by BlackthornYugen** [comment]
> Maybe `RUN yarn version "$(git describe --tags --dirty)"` works.

Tried that but it doesn't work in the build at the moment.

```
 > [builder 5/7] RUN yarn version "$(git describe --tags --dirty)":
0.616 Usage Error: No ancestor could be found between any of HEAD and master, origin/master, upstream/master, main, origin/main, upstream/main
0.616 
0.616 $ yarn version [-d,--deferred] [-i,--immediate] <strategy>
------
Dockerfile:18
--------------------
  16 |     
  17 |     # RUN jq '.version=$VERSION' package.json --arg VERSION "$(git describe --tags --dirty)" | sponge package.json
  18 | >>> RUN yarn version "$(git describe --tags --dirty)"
  19 |     RUN yarn install
  20 |     RUN yarn build
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn version \"$(git describe --tags --dirty)\"" did not complete successfully: exit code: 1
```

 It works locally but it's doing extra stuff too? 

```
mongo-express git:(release/v1.0.2) ✗ yarn version "$(git describe --tags --dirty)"
➤ YN0000: mongo-express@workspace:.: Bumped to 1.0.2-1-g5aaff6f-dirty

➤ YN0000: ┌ Resolution step
➤ YN0060: │ mongo-express@workspace:. provides babel-loader (pc43ad) with version 9.1.2, which doesn't satisfy what @cypress/code-coverage and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0007: │ cypress@npm:12.5.1 must be built because it never has been before or the last one failed
➤ YN0007: │ mongodb-memory-server@npm:8.11.4 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ spawn-sync@npm:1.0.15 must be built because it never has been before or the last one failed
➤ YN0007: │ pre-commit@npm:1.2.2 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 19s 996ms
➤ YN0000: Done with warnings in 20s 294ms
➜  mongo-express git:(release/v1.0.2) ✗ cat package.json 
{
  "version": "1.0.2-1-g5aaff6f-dirty",
...
```

**Comment by BlackthornYugen** [comment]
If I have it checkout the release branch instead of the tag, the package.json will be correct already. I'll try that.

**Review by rtritto — APPROVED** [review]
LGTM!

**Pull request merged**
