### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by shakaran**

### CODE REVIEW

**Comment by xTudoS** [comment]
Once codeql doesn't support bash, can we close this PR? @shakaran @rtritto

**Comment by rtritto** [comment]
@xTudoS what's the error in logs? (Logs are expired)

**Comment by xTudoS** [comment]
> @xTudoS what's the error in logs? (Logs are expired)

[Analyze (python)](https://github.com/mongo-express/mongo-express-docker/actions/runs/7942720504/job/21686298136#step:5:84)
Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.16.2/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14567 /home/runner/work/_temp/codeql_databases/python". Exit code was 32 and last log line was: CodeQL did not detect any code written in languages supported by CodeQL. Review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . See the logs for more details

**Comment by rtritto** [comment]
You're right, Bash isn't supported by CodeQL ([source](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks))

**Pull request closed without merging**
