### PR TITLE
Update to 0.44.0

### PR DESCRIPTION
**Pull request by tianon**
:heart:

### CODE REVIEW

**Comment by knickers** [comment]
Thanks! Will you build this and make sure it runs?

**Comment by tianon** [comment]
Ok, combined #8, did a full build test, fired it up against a `mongo:3.6` instance, everything launched just fine, was able to successfully create collections and documents. :+1:

**Comment by knickers** [comment]
Amazing! Thank you!

**Comment by tianon** [comment]
Awesome, I'll give you a poke as soon as I've got a PR to https://github.com/docker-library/official-images up. :+1:

**Pull request merged**
