### PR TITLE
Update to 0.52.1

### LINKED ISSUE #29: Update to version 0.52.1
Hello, @tianon @knickers!

I'd like to reach out to you and ask if you can please update the project to the 0.52.1 version, as it adds a new feature to support secrets on docker with _FILE suffix

Thanks!

### PR DESCRIPTION
**Pull request by tianon**
Verified this builds, runs, and that I'm able to make changes in the MongoDB instance I pointed it at.

Closes #29

@knickers what do you think about adding some automation for these bumps? (we use @docker-library-bot to do a lot of automation for the other repos we maintain; I'd be happy to set it up here too if you wanted me to)

It'd be really cool if we could come up with a simple automated test we could run against new releases too, but maybe that's asking too much?

### CODE REVIEW

**Comment by knickers** [comment]
Yeah I would love some automation 😃 I didn't know there was any available for official images. Is the bot able to make http requests to containers? Maybe we could just check for `200 OK` response.

**Comment by tianon** [comment]
Yeah!  https://github.com/docker-library/official-images/blob/master/test/tests/wordpress-apache-run/run.sh is an example test that's probably even slightly more than we need initially here.  I think if we get `200 OK`, we probably know we connected to MongoDB successfully, so I'll get a PR up over there and give you a ping once I've got it so we can discuss automation further once you're happy with the automated tests.  Sound fair?

(Maybe I should manually bump this to the new 0.52.2 release in the meantime?)

**Comment by ErikAbele** [comment]
Awesome, +1 to automation and the test (which works here too).

**Comment by damien-malescot** [comment]
Hi,

Any news on this feature ? We just fix an issue in version 0.53 and I need image to pull it in my openshift registry?

I prefer official image than make it myself on private repo.

Thx!

**Comment by tianon** [comment]
Hey @knickers, what do you think about making myself and/or @docker-library-bot as comaintainers on this repo so we can get this back up-to-date? (and maybe apply https://github.com/docker-library/official-images/pull/5697 or something like it so we can automate keeping it up to date?) :pray: :heart:

**Comment by knickers** [comment]
Oh geez :man_facepalming: I must have my notification settings turned off somewhere because I didn't know you had done work on the bot already :cry: Thank you for pinging me here, I have some time to look at it right now.

**Comment by tianon** [comment]
See https://github.com/mongo-express/mongo-express-docker/commit/4b43fe8a1206434cb32a006cd155dd71462f092f and https://github.com/docker-library/official-images/pull/7394 :tada: :+1:

**Pull request closed without merging**
