### PR TITLE
Moved the docker entrypoint to a lower layer

### LINKED ISSUE #94: Move copy down in dockerfile
As pointed out in #93, we should copy the entrypoint as far down as possible. It should especially be below RUN steps that need to install / download artifacts from the internet. 

https://github.com/mongo-express/mongo-express-docker/pull/93#discussion_r1342899510

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Fixes #94

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@BlackthornYugen you beat me to it but thise one removes the setting the executable because it's not needed anymore

**Comment by BlackthornYugen** [comment]
> @BlackthornYugen you beat me to it but thise one removes the setting the executable because it's not needed anymore

I also forgot to run the update script :)

**Review by BlackthornYugen — APPROVED** [review]
Looks good, but it bumps to 1.0.1. I want to see if I can release 1.0.0 before I merge this.

**Comment by LaurentGoderre** [comment]
Good catch!

**Comment by LaurentGoderre** [comment]
Updated

**Review by BlackthornYugen — APPROVED** [review]

**Pull request merged**
